### ISSUE TITLE
Can tell me how to run this code

### ISSUE THREAD

**Issue by Kusumadhanush22** [safvanck/Handwriting-Analysis-for-Detection-of-Personality-Traits#1]

**Comment by AreRex14** [comment]
@Kusumadhanush22 Don't you read the README description?

**Comment by KaiwanRanderia** [comment]
Says can't fine model_json file

**Comment by mayurp-yb** [comment]
Which python version is used?

**Comment by safvanck** [comment]
> Says can't fine model_json file

@KaiwanRanderia 
model_json file will be creatted once the training is completed

**Comment by workspace-utkarsh** [comment]
Which version of python is used while running the project?

**Comment by globalenergypvtltd** [comment]
> Says can't fine model_json file

Yes!  I am facing the same issue. Could you please let me know it you find the solution

**Comment by RanjeetaHardi** [comment]
> Says can't fine model_json file

Yes!  I am facing the same issue. Could you please let me know it you find the solution

**Comment by RanjeetaHardi** [comment]
Epoch 97/100
14/14 [==============================] - 10s - loss: 4.1895e-05 - acc: 1.0000 - val_loss: 1.8974 - val_acc: 0.2857
Epoch 98/100
14/14 [==============================] - 11s - loss: 3.6895e-05 - acc: 1.0000 - val_loss: 1.9031 - val_acc: 0.2857
Epoch 99/100
14/14 [==============================] - 11s - loss: 8.8632e-05 - acc: 1.0000 - val_loss: 1.8672 - val_acc: 0.2857
Epoch 100/100
14/14 [==============================] - 11s - loss: 5.5804e-05 - acc: 1.0000 - val_loss: 1.8833 - val_acc: 0.2857
Test loss: 1.8832799196243286
Test accuracy: 0.2857142984867096
Traceback (most recent call last):
  File "C:\Users\LENOVO\Desktop\Handwriting-Analysis-for-Detection-of-Personality-Traits-master\model_training.py", line 127, in <module>
    with open(model_json_path, "w") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'model_files/model.json'


This is the error i am facing please let me know the solution.
