### ISSUE TITLE
um, invert error!

### ISSUE THREAD

**Issue by ashutosh215** [safvanck/Handwriting-Analysis-for-Detection-of-Personality-Traits#2]
when i run python model_training.py

i get the following error 

cpy = cv2.dilate(~cpy, struct, anchor=(-1, -1), iterations=1)
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by safvanck** [comment]
@ashutosh215 
which version of opencv you are using?

**Comment by safvanck** [comment]
re-install the package with: opencv-python==3.4.5.20 solves the issue
